kind: pipeline
name: default
type: docker

steps:
  - name: Restore cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "{{ .Repo.Owner }}-{{ .Repo.Name }}-{{ .Commit.Branch }}"
      archive_format: "gzip"
      mount:
        - 'go-build-cache'
    volumes:
      - name: cache
        path: /tmp/cache

  - name: Build & Test
    pull: if-not-exists
    image: golang
    commands:
      - mv go-build-cache /root/.cache/go-build
      - go build
      - go test -v ./...
      - mv /root/.cache/go-build go-build-cache
    volumes:
      - name: cache
        path: /go

  # - name: Build Docker container
  #   pull: if-not-exists
  #   image: docker
  #   commands:
  #     - docker build -t rtcv:latest .
  #   volumes:
  #     - name: dockerSocket
  #       path: /var/run/docker.sock

  - name: Rebuild cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "volume"
      archive_format: "gzip"
      mount:
        - 'go-build-cache'
    volumes:
      - name: cache
        path: /tmp/cache

# trigger:
#   branch:
#     - main

volumes:
  - name: dockerSocket
    host:
      path: /var/run/docker.sock
  - name: cache
    temp: {}
